### ISSUE TITLE
Implement missing SortedSet, TTL, and Scalar APIs in client-sdk-php

### ISSUE THREAD

**Issue by rishtigupta** [momentohq/client-sdk-php#213]
https://www.notion.so/momentohq/Momento-Replacement-Drop-in-Client-for-phpredis-11bfeb15c97d8078b461fc3ee09260f6

## Sorted set
- [x] sortedSetPutElement
- [x] sortedSetPutElements - Nate
- [x] sortedSetIncrementScore - Michael
- [x] sortedSetRemoveElement - rishti
- [x] sortedSetRemoveElements - Michael
- [x] sortedSetLengthByScore - Nate
- [x] sortedSetGetScore - Michael
- [x] sortedSetFetchByRank
- [x] sortedSetFetchByScore - Nate

## Ttl
- [x] updateTtl
- [x] increaseTtl
- [x] decreaseTtl
- [x] itemGetTtl

## Scalar
- [x] setIfAbsent
- [x] setIfPresent

## Dev docs
- [x] Update doc example snippets (can be sequenced after plugin development)

**Comment by danielamiao** [comment]
@malandis to help complete the doc above for customer review

**Comment by malandis** [comment]
I updated the Notion document with detail not just on the various commands, but specific options and return values as well. See [this section](https://www.notion.so/momentohq/Momento-Replacement-Drop-in-Client-for-phpredis-11bfeb15c97d8078b461fc3ee09260f6?pvs=4#11ffeb15c97d8074b823cf66d8e6b5bf).

**Comment by malandis** [comment]
Nate:
- sortedSetPutElements
- sortedSetFetchByRank

Michael:
- sortedSetGetScore
- sortedSetIncrementScore

**Comment by malandis** [comment]
get score: https://github.com/momentohq/client-sdk-php/pull/221
remove elements: https://github.com/momentohq/client-sdk-php/pull/227
increment score: https://github.com/momentohq/client-sdk-php/pull/229
