### ISSUE TITLE
Use PSR-16 for Momento\Cache\SimpleCacheClient

### ISSUE THREAD

**Issue by onethumb** [momentohq/client-sdk-php#40]
The PHP-FIG defined an industry-standard interface ([PSR-16](https://www.php-fig.org/psr/psr-16/)) for working with caches, it'd be nice if Momento followed the community on this since it'd reduce friction and increase adoption.

**Comment by cprice404** [comment]
@onethumb thanks for the suggestion!  Our PHP SDK is a recent addition for us, so we are still working on adding some integrations such as the Laravel caching facade.  We will definitely provide an implementation of PSR-16, thanks for pointing it out.

**Comment by onethumb** [comment]
FWIW, for future work around additional possible platform features like add / increment / decrement, we have an internal `Interface` which looks like this: https://gist.github.com/onethumb/10d60b8f8648a14092efacabee058dd1

**Comment by cprice404** [comment]
Excellent, thanks.  We'll get the PSR one done first and then think about what would be a good way to handle the expanded version.

**Comment by cprice404** [comment]
@onethumb for operations such as `setMultiple` or `getMultiple`, what would you typically expect to be the maximum size for an individual request?  e.g. how many keys, and how large are the values?

In poking around existing implementations of the PSR I don't see any occasions where maximum sizes are explicitly specified, but I would assume that for a PHP there is a practical limit and that it's somewhere in the range of, say, a few MB?

**Comment by pgautier404** [comment]
@onethumb thanks so much for your suggestion. We've added an initial basic PSR-16 implementation in version 0.2.2 of the SDK. Let us know if there's anything else we can do to help you evaluate Momento, such as providing an implementation of your `ExtendedCacheInterface`.
