### ISSUE TITLE
Use strict types

### ISSUE THREAD

**Issue by onethumb** [momentohq/client-sdk-php#41]
Given your PHP >=7.4 requirement, it'd be nice if your code all used `declare(strict_types=1);` since you don't have a backwards-compatibility concern.

I'd argue you should drop the 7.4+ requirement, given it's End Of Life (including security updates) date is November 28, 2022, which will let you use many more advanced type hints with PHP 8.0+. :)

**Comment by pgautier404** [comment]
Great suggestions, thanks for the feedback! We've added strict types and bumped the minimum version requirement to 8.0.
