### ISSUE TITLE
Rename dictionary and set read/write functions

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-php#52]

**Comment by cprice404** [comment]
Final names should be:

DictionaryGetField, DictionaryGetFields, DictionarySetField, DictionarySetFields, DictionaryRemoveField, DictionaryRemoveFields, SetAddElement, SetAddElements, SetRemoveElement, SetRemoveElements

**Comment by poppoerika** [comment]
Already named as suggested above:

- `DictionaryRemoveField`
- `DictionaryRemoveFields`

APIs have not been implemented:

- `SetAddElements`
- `SetRemoveElement`
- `SetRemoveElements`
